# Generated by Django 5.0.4 on 2024-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
    ]
